name: Build report

on:
  push:
    branches: [main]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: typst-community/setup-typst@fee4b65b091cc546f02ce3be15fad8760f38a108 # v5.3.0
      - uses: fontist/setup-fontist@19acfdc47b0f43fe7d441052821539ca584d7809 # v2.1.0
      - run: fontist install 'Atkinson Hyperlegible Next'
      - run: |
          typst compile main.typ build/report.pdf --pdf-standard ua-1
          typst compile main.typ build/report.html --features html --format html
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: report
          path: build/report.*
